<?php

namespace Stades\StadesBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TypeTerrainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeTerrainRepository extends EntityRepository
{
}
